### PR TITLE
Added Cheaha > Getting Started Page

### PR DESCRIPTION
**Pull request by jgordini**
Not sure if this is correct but converted the existing Getting Started page to Markdown and fixed the links. Some links go to pages that don't exist yet.

### CODE REVIEW

**Comment by jgordini** [comment]
I'm happy to pull some of the articles off media wiki and convert them to markdown, if this helps you. I don't want to get in the way of your process. Also if there are any that you would like to focus on I could also do those first.

**Review by mdefende — APPROVED** [review]
Thanks for transferring this. We needed a Getting Started page for the new docs but hadn't gotten around to converting it. We will merge this and prune off some of the deprecated information and add links to the other locations in the docs that are relevant for the material in here. You doing the conversion and linting beforehand saves us a good amount of work though, so thanks for that!

**Comment by bjoyce3** [comment]
@jgordini We've moved most of the other UABgrid docs that need to be moved (there was some splitting that happened to break up the really big sections too). 

But we do have a fairly large Issues section if anything in there strikes your interest! Also feel free to leave us feedback/suggestions there too.

**Comment by bjoyce3** [comment]
Fixes https://github.com/uabrc/uabrc.github.io/issues/85

**Pull request merged**
