### PR TITLE
CSS Styling fixes and dropshadow

### LINKED ISSUE #110: Consider using drop shadows for images for visibility
CSS Hacks: https://github.com/squidfunk/mkdocs-material/issues/1635

Drop Shadow CSS function documentation: https://developer.mozilla.org/en-US/docs/Web/CSS/filter-function/drop-shadow()

image

The change would be made in [extra.css](https://github.com/uabrc/uabrc.github.io/blob/fc29dba/docs/stylesheets/extra.css)

### PR DESCRIPTION
**Pull request by jgordini**
I have added styling fixes for an alignment issue. Added margins for when images are aligned to the left and the right. 
I have also added code for the drop shadow and cropped images in the cloud docs to fix spacing.  

Fixes #110 (Edit by wwarriner)

### CODE REVIEW

**Comment by jgordini** [comment]
Image of the alignment issue.

Screen Shot 2022-03-09 at 11 55 42 AM

Iamge of the fix. 

Screen Shot 2022-03-09 at 11 34 14 AM

**Comment by jgordini** [comment]
you can see the changes I have made here. https://jgordini.github.io/uabrc.github.io/uab_cloud/network_setup_basic/

**Review by bjoyce3 — APPROVED** [review]

**Comment by bjoyce3** [comment]
@jgordini we were able to fix a bunch of things in the main structure of the docs. Could you pull the upstream changes so I can merge your PR? I think most of the merge conflicts are just text that's changed in the articles.

**Comment by mdefende** [comment]
When I try to review the pull request changes, none of them show up. is it possible you pulled from the `uabrc:main` branch into your main and overwrote the changes you had?

**Pull request closed without merging**
