### PR TITLE
Removes >< centering tag

### PR DESCRIPTION
**Pull request by mdefende**
removes previous centering CSS tag since that is automatically applied to all images from request #209

### CODE REVIEW

**Comment by wwarriner** [comment]
The change made in #201 will need to be undone here.

Is this change meant to include changes to the /docs/stylesheets/extra.css file?

**Comment by wwarriner** [comment]
Oh nevermind the question, I see that change was made in #209

**Comment by mdefende** [comment]
Yeah, it shouldn't have touched the extra.css file, just removing the tags from the alt text box

**Review by bjoyce3 — COMMENTED** [review]
A whole lotta >< deletes. Good deal

**Pull request merged**
