### PR TITLE
Visual Brain Core

### PR DESCRIPTION
**Pull request by jgordini**
Adding Visual Brain Core Page updated with new links.

# Pull Request

### CODE REVIEW

**Comment by wwarriner** [comment]
Hey @jgordini, I appreciate the effort in reformatting the page. Content-wise the page needs some work to remove/update obsolete content. It has office hours that no longer exist for example. I think that Ravi is no longer funded by the brain core, so we have no official ties to support them (that I know of).

Given that the brain core isn't directly related to Research Computing, I don't want to commit to maintaining a page for someone else's group.

To address a specific part of that page, at the end: we're moving away from providing programming and science-specific support. We're happy to install software and show how to get that software running on Cheaha, how to use parallel computing facilities, how to do all the stuff surrounding scientific computing. We won't provide software development support nor make strong recommendations about what software is best for a given use case. Maybe if we ever get an RSE subgroup going we can do that, but we aren't there right now.

**Comment by jgordini** [comment]
As this is more related to overall strategy I would like to defer to kmv@uab.edu and mdefende@uab.edu for comments. I am just supplying some technical support and am not sure of the overall goals of the project.

**Comment by wwarriner** [comment]
Sure, and appreciated! I definitely will defer to those more in the know than I am on this.

**Comment by jgordini** [comment]
Closed pending further investigation.

**Pull request closed without merging**
