### PR TITLE
Software Container page

### LINKED ISSUE #88: Containerization page
Having a containerization page would be helpful.

https://cloud.sylabs.io/builder is also useful when root and --fakeroot aren't possible.

### PR DESCRIPTION
**Pull request by Premas**
Included Software container writeup. It's the first draft and requires addressing a few review comments:

1. Cropping all images retaining necessary information.
2. Fixing bash scripts
3. Add section "Creating your own Docker container"
4. Building containers with a version tag
5. Working on Hyperlinking/cross-referencing
6. Organizing the section "Sharing containers using UAB GitLab Container Registry"

Fixes #88

### CODE REVIEW

**Comment by Premas** [comment]
@wwarriner reviewed the first draft of this software container page. I am working to address the listed six review comments.

**Comment by Premas** [comment]
@bjoyce3 please review the Software Container page. Reviewed and made changes to the Software Container page. Fixed the six review comments suggested by @wwarriner. In addition, added a section "Run Docker interactively" to this page.

**Comment by bjoyce3** [comment]
Branch is 32 commits behind main. Requesting an upstream pull to resolve merge conflicts while reviewing with @Premas .

**Comment by bjoyce3** [comment]
TODO:
- go through and check headers/titles for capitalization
- Double check admonitions by doing local `mkdocs serve`: https://uabrc.github.io/contributor_guide/#false-positive-lint-warnings-from-admonitions
- 

1. Cropping all images retaining necessary information. 
**Looks great**
3. Fixing bash scripts (not formatted correctly as code blocks)
**Bash commands have been formatted correctly**
4. Add section "Creating your own Docker container"
   - add software versions for scipy, matplotlib
   - edit the containers and reproducibility admonition as needed
   - Step 2 (and all other changes) add in "Where Am I Now?" transitions. Either screenshots of the terminal with the command or a picture of the terminal so people have context.
6. Building containers with a version tag
**edited and this is probably enough for now**
8. Working on Hyperlinking/cross-referencing
**Fix doc internal links:**
-  Documentation file 'workflow_solutions/getting_containers.md' contains a link to 'workflow_solutions/images/containers docker_hub_website.png' which is not found in the documentation files
-  Documentation file 'workflow_solutions/getting_containers.md' contains a link to '../docs/account_management/gitlab_account.md' which is not found in the documentation files.
9. Organizing the section "Sharing containers using UAB GitLab Container Registry"
- Add context of when you're on a GitLab webpage getting information and when you're using information in terminal.
- Fix up "Push Alpine Container from Ubuntu system to UAB GitLab container registry." step to either be an example or a series of steps
- Put in default suggestions for token creation settings
- Explain any warnings in the images in the docs like "Warning! Using --password will be stored unencrypted in /root/.docker"
-

**Comment by Premas** [comment]
@bjoyce3 : Please review the changes.

Incorporated the following changes to Software Container Page:

1. Fixed header capitalization. Verified admonitions, and looks good to me.
2. Incorporated Changes to "Creating your Own Docker Container".
  a. In the specification/Dockerfile, added software versions for numpy, scipy and matplotlib.
  b. Containers and reproducibility admonition looks good to me.
  c. Added screenshots to elaborate on the transition and steps.
3. Fixed hyperlinking for internal links.
4. Incorporated Changes to "Sharing containers using UAB GitLab Container Registry"
a. The transitions from the `Gitlab's container page' to the System and vice versa are now taken care of.
b. Fixed "Push Alpine Container from your System to UAB GitLab container registry" as a series of steps, and organized the write-up.
c. Added default suggestions for token creation.
d. Included a `warning` admonition for docker login message, "Warning! Using --password will be stored unencrypted in /root/.docker"

**Comment by wwarriner** [comment]
Great stuff Prema! Take a look at the couple comments I left in the code, clean up the images, and I think we can merge it at the point. Thanks!

**Comment by Premas** [comment]
@wwarriner Please review. I had incorporated changes to the images: Cropping, Including text and highlights to add clarity to the images.

**Review by wwarriner — APPROVED** [review]

**Pull request merged**
